In [1]:
from PIL import Image
import numpy as np
import os
import cv2

In [2]:
img = np.array(Image.open('./Set5/baby.png'))

In [3]:
img.dtype

dtype('uint8')

In [6]:
h,w,_ = img.shape
print("h: ", h, "w: ", w)

h:  512 w:  512


In [7]:
img = img[:,:,0]

In [8]:
img

array([[252, 252, 252, ..., 254, 254, 254],
       [252, 252, 252, ..., 254, 254, 254],
       [252, 252, 252, ..., 254, 254, 254],
       ...,
       [ 77,  85,  86, ...,  63,  63,  63],
       [ 68,  72,  74, ...,  65,  64,  64],
       [ 63,  66,  67, ...,  66,  66,  65]], dtype=uint8)

use Image.fromarray

In [10]:
PIL_bilinear = Image.fromarray(img).resize([1024,1024], resample=Image.BILINEAR)

In [11]:
np.array(PIL_bilinear)

array([[252, 252, 252, ..., 254, 254, 254],
       [252, 252, 252, ..., 254, 254, 254],
       [252, 252, 252, ..., 254, 254, 254],
       ...,
       [ 67,  68,  70, ...,  65,  64,  64],
       [ 64,  65,  67, ...,  66,  65,  65],
       [ 63,  64,  65, ...,  66,  65,  65]], dtype=uint8)

In [12]:
np.array(PIL_bilinear).shape

(1024, 1024)

use transform

In [15]:
from scipy import interpolate
def bilinear(img, scale):
    '''
        if img.shape = [2,2], output.shape = [2*scale-1, 2*scale-1]
        e.g. scale = x2, the kernel for bilinear is 4
        so when h,w = img.shape, the bilinear upsampled image is 2*h-1, 2*w-1,
    '''
    img = np.float32(img)
    h, w = img.shape
    hgrid = np.linspace(0, h-1, h)
    wgrid = np.linspace(0, w-1, w)
    bilinearInterp = interpolate.interp2d(wgrid, hgrid, img, kind="linear")
    hgrid = np.linspace(0, h-1, h*scale-1)
    wgrid = np.linspace(0, w-1, w*scale-1)
    upsampled = bilinearInterp(wgrid, hgrid)
    return upsampled

In [16]:
bilinear(img, 2)

array([[252.  , 252.  , 252.  , ..., 254.  , 254.  , 254.  ],
       [252.  , 252.  , 252.  , ..., 254.  , 254.  , 254.  ],
       [252.  , 252.  , 252.  , ..., 254.  , 254.  , 254.  ],
       ...,
       [ 68.  ,  70.  ,  72.  , ...,  64.  ,  64.  ,  64.  ],
       [ 65.5 ,  67.25,  69.  , ...,  65.  ,  64.75,  64.5 ],
       [ 63.  ,  64.5 ,  66.  , ...,  66.  ,  65.5 ,  65.  ]])

In [17]:
bilinear(img, 2).shape

(1023, 1023)

use opencv2

In [24]:
cv2.resize(img.astype(np.float32), (0,0), fx=2, fy=2, interpolation=cv2.INTER_LINEAR)

array([[252.    , 252.    , 252.    , ..., 254.    , 254.    , 254.    ],
       [252.    , 252.    , 252.    , ..., 254.    , 254.    , 254.    ],
       [252.    , 252.    , 252.    , ..., 254.    , 254.    , 254.    ],
       ...,
       [ 66.75  ,  67.6875,  69.5625, ...,  64.4375,  64.3125,  64.25  ],
       [ 64.25  ,  65.0625,  66.6875, ...,  65.3125,  64.9375,  64.75  ],
       [ 63.    ,  63.75  ,  65.25  , ...,  65.75  ,  65.25  ,  65.    ]],
      dtype=float32)

In [22]:
cv2.resize(img.astype(np.float32), (1023,1023),  interpolation=cv2.INTER_LINEAR)

array([[252.     , 252.     , 252.     , ..., 254.     , 254.     ,
        254.     ],
       [252.     , 252.     , 252.     , ..., 254.     , 254.     ,
        254.     ],
       [252.     , 252.     , 252.     , ..., 254.     , 254.     ,
        254.     ],
       ...,
       [ 66.75611,  67.69666,  69.57411, ...,  64.43567,  64.31116,
         64.24878],
       [ 64.25366,  65.06873,  66.69569, ...,  65.31213,  64.93713,
         64.74927],
       [ 63.     ,  63.7522 ,  65.25366, ...,  65.75122,  65.25073,
         65.     ]], dtype=float32)

In [28]:
timage = np.array([[1,3],[3,5]], dtype=np.float32)

In [29]:
timage

array([[1., 3.],
       [3., 5.]], dtype=float32)

In [32]:
cv2.resize(timage.astype(np.float32), (4,4),  interpolation=cv2.INTER_LINEAR)

array([[1. , 1.5, 2.5, 3. ],
       [1.5, 2. , 3. , 3.5],
       [2.5, 3. , 4. , 4.5],
       [3. , 3.5, 4.5, 5. ]], dtype=float32)